 # Generated by Django 4.2.7 on 2023-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.FloatField()),
                ('soil', models.FloatField()),
                ('light', models.FloatField()),
                ('air_temp', models.FloatField()),
                ('day', models.DateTimeField()),
            ],
        ),
    ]
