# Generated by Django 4.2.7 on 2023-12-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_day_timeline_remove_moisture_day_moisture_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='day',
            table='day',
        ),
        migrations.AlterModelTable(
            name='moisture',
            table='moisture',
        ),
        migrations.AlterModelTable(
            name='timeline',
            table='timeLine',
        ),
    ]
